(function(){'use strict';var m=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},n=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},q=n(this),r=function(a,b){if(b)a:{var c=q;a=a.split(".");for(var d=
0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&m(c,a,{configurable:!0,writable:!0,value:b})}};r("globalThis",function(a){return a||q});
r("String.prototype.matchAll",function(a){return a?a:function(b){if(b instanceof RegExp&&!b.global)throw new TypeError("RegExp passed into String.prototype.matchAll() must have global tag.");var c=new RegExp(b,b instanceof RegExp?void 0:"g");b instanceof RegExp&&(c.lastIndex=b.lastIndex);var d=this,f=!1,e={next:function(){if(f)return{value:void 0,done:!0};var k=c.exec(d);if(!k)return f=!0,{value:void 0,done:!0};k[0]===""&&(c.lastIndex+=1);return{value:k,done:!1}}};e[Symbol.iterator]=function(){return e};
return e}});function t(a){var b,c=!1;return async()=>{if(c)return b;b=await a();c=!0;return b}}function u(a){return[...a.querySelectorAll("script")].filter(b=>b.src.includes("googletagmanager.com/gtag/js")||b.src.includes("googletagmanager.com/gtm.js")||b.src.includes("google.com/gtag/js")||b.src.includes("google.com/gtm.js")||b.innerText.includes("google_tags_first_party"))};var v={type:5},w=class{constructor(a){this.h=a;this.C=async()=>{try{if((await this.h.fetch("https://www.googletagmanager.com/gtag/js?id=DUMMY",{method:"HEAD",mode:"no-cors",cache:"no-store"})).redirected)return v;let b=await (await this.h.fetch("https://www.googletagmanager.com/gtag/js?id=DUMMY")).text();return["DUMMY","google_tag_data","google_tag_manager","/debug/bootstrap?id="].every(c=>b.includes(c))?null:v}catch(b){return v}};this.i=t(this.C)}init(){}destroy(){}};var x={axeptioSDK:17,tC:8,cmplz_set_consent:15,cmpmngr:4,Cookiebot:3,cookiefirst_show_settings:16,cookiehub:22,CookieInformation:9,CLI:20,Osano:10,SP_SCRIPT_CONF:19,SDDAN:14,Termly:12,OneTrust:6,UC_UI:2,cookieyes:11,Didomi:7,TrustArc:13,CookieScript:18,Iubenda:5},y=class{constructor(a){this.h=a}init(){}async i(){var a=[],b=this.h;for(let c in x)b[c]!==void 0&&a.push(x[c]);return a.length>0?{type:6,detectedCmps:a}:null}destroy(){}};var z=class{constructor(a){this.h=a;this.violations=[];this.L=b=>{this.violations.push(b)}}init(){this.h.addEventListener("securitypolicyviolation",this.L)}async i(){return this.violations.filter(a=>a.blockedURI.includes("googletagmanager.com/gtag/js")||a.blockedURI.includes("googletagmanager.com/gtm.js")||a.blockedURI.includes("google.com/gtag/js")||a.blockedURI.includes("google.com/gtm.js")).length>0?{type:9,blockedUrls:this.violations.map(a=>a.blockedURI),violatedDirectives:this.violations.map(a=>
a.violatedDirective)}:null}destroy(){this.violations=[];this.h.removeEventListener("securitypolicyviolation",this.L)}};function A(a){var b=B(a),c=C(a,b),d=a.src,f=a.innerText;if(b===0)return[{o:!1,snippetType:b,errorType:1,scriptSrc:d,scriptContent:f}];if(b===4)return c.map(e=>({o:!1,snippetType:b,tagId:e,errorType:3,scriptSrc:d,scriptContent:f}));a=[];for(let e of c)e&&(e.startsWith("GTM-")||e.startsWith("G-")||e.startsWith("GT-")||e.startsWith("AW-")||e.startsWith("FL-")||e.startsWith("GA-")||e.startsWith("DC-"))||a.push({o:!1,snippetType:b,tagId:e,errorType:3,scriptSrc:d,scriptContent:f});return a.length?a:c.map(e=>
({o:!0,snippetType:b,tagId:e,scriptSrc:d,scriptContent:f}))}function B(a){return a.src.includes("googletagmanager.com/gtag/js")||a.src.includes("google.com/gtag/js")?1:a.src.includes("googletagmanager.com/gtm.js?")||a.src.includes("google.com/gtm.js")?2:a.innerText.includes("google_tags_first_party")?D(a).length>0?3:4:0}function C(a,b){if(b===1||b===2){a:{try{let d;var c=(d=(new URL(a.src)).searchParams.get("id"))!=null?d:void 0;break a}catch(d){}c=void 0}return(a=c)?[a]:[]}return D(a)}
function D(a){var b=a.innerText.match(/window,'([^&]+)','google_tags_first_party'/);if(b)return[b[1]];b=a.innerText.match(/window,\[(.*?)\],'google_tags_first_party'/);a=[];if(b&&b[1]){b=b[1].matchAll(/'([^']+)'/g);for(let c of b)a.push(c[1])}return a};var E=class{constructor(a){this.h=a}init(){}async i(){var a=u(this.h.document);for(let b of a){a=A(b);for(let c of a)if(!c.o)return{type:8,snippetType:c.snippetType,tagId:c.tagId,errorType:c.errorType,scriptSrc:c.scriptSrc,scriptContent:c.scriptContent}}return null}destroy(){}};var F=class{constructor(a){this.h=a}init(){}async i(){var a={type:3};return this.h.navigator.onLine?null:a}destroy(){}};var G=class{constructor(a){this.h=a}init(){}async i(){var a=this.h;a=!!(a["google.tagmanager.debugui2.queue"]||a["google.tagmanager.ta.prodqueue"]||a.google_tag_data);var b=u(this.h.document);return a||b.length!==0?null:{type:4}}destroy(){}};var aa=class{constructor(a){this.h=a;this.C=async()=>await J(this.h.location.href)?null:{type:7};this.i=t(this.C)}init(){}destroy(){}};async function J(a){try{return(await fetch(a,{method:"HEAD",mode:"no-cors",cache:"no-store"})).status<400}catch(b){return!1}};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ba=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var ca=class{constructor(){this.N=void 0;this.m=!1;this.u=[]}addListener(a){if(this.m)return()=>{};this.u.push(a);return()=>{this.removeListener(a)}}destroy(){this.m||(this.u=[],this.N&&this.N(),this.m=!0)}removeListener(a){if(!this.m){var b=this.u;a=ba(b,a);a>=0&&Array.prototype.splice.call(b,a,1)}}};var K=function(a){a.A=a.A.then(async()=>{var b=await da(a),c;if((c=a.v)!=null&&!c.m){c=[...c.u];for(let d=0;d<c.length;d++)try{c[d](b)}catch(f){console.log("Event listener failed",f)}}})},L=function(a){if(!a.J&&(a.h.document.head||a.h.document.body)){a.J=!0;a.P=Date.now();for(let b of a.F)b.l!==void 0?b.l.init():b.init();a.R=setInterval(()=>{K(a)},1E3);K(a)}},ea=function(a,b){a.v.addListener(b)},da=async function(a){return{issues:(await Promise.all(a.F.map(b=>b.l!==void 0?b.timeoutMs&&Date.now()-
a.P<b.timeoutMs?Promise.resolve(null):b.l.i():b.i()))).filter(b=>b!==null),pageUrl:a.h.location.href}},fa=class{constructor(a){this.h=a;this.v=new ca;this.J=!1;this.P=0;this.A=Promise.resolve();this.F=[new F(a),new E(a),new aa(a),new z(a),new w(a),new y(a),{l:new G(a),timeoutMs:5E3}]}destroy(){var a;(a=this.v)==null||a.destroy();this.v=void 0;this.A=Promise.resolve();clearInterval(this.R);for(let b of this.F)b.l!==void 0?b.l.init():b.init()}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var M=globalThis.trustedTypes,N;function ha(){var a=null;if(!M)return a;try{let b=c=>c;a=M.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var ia=class{constructor(a){this.V=a}toString(){return this.V+""}};function O(a){var b;N===void 0&&(N=ha());a=(b=N)?b.createScriptURL(a):a;return new ia(a)};function P(a,...b){if(b.length===0)return O(a[0]);var c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return O(c)};function Q(a){a.endsWith("/")}P`cs/ta/tag_assistant_api_bin.js`;P`cs/ta/content_script_bin.js`;P`cs/ta/start_debug_content_script_bin.js`;P`cs/ta/start_prod_debug_content_script_bin.js`;P`cs/gf/guided_flows_content_script_bin.js`;Q("https://tagassistant.google.com/guided_flows/open");Q("https://tagassistant.google.com");Q("https://tagassistant.google.com/embedded/side_panel");function R(a){return a.length>1E4?a.substring(0,9997)+"...":a}
var S=function(a,b,c=null){if(b==null)return b;var d=typeof b;if(d==="boolean"||d==="number")return b;if(d==="string")return R(b);if(d==="function")return"Function";if(d==="object"){let g=a.H.indexOf(b);if(g!==-1){a.cycles[c]=a.I[g];return}try{if(b&&typeof b[Symbol.iterator]==="function"){var f=[];a.H.push(b);a.I.push(c);var e=0;for(var k of b)f.push(S(a,k,c==null?`${e}`:`${c}.${e}`)),e++;return f}if(b instanceof Node){a=[];c=b;do{if(c instanceof Element){let H=c.classList?[...c.classList].join("."):
"",I=(c.tagName?c.tagName.toLowerCase():"")+(H?"."+H:"")+(c.id?"#"+c.id:"");I&&a.unshift(I)}c=c.parentNode}while(c!=null);var h;let l=(h=(e=b.toString().match(/\[object (\w+)\]/))==null?void 0:e[1])!=null?h:b.toString(),p=a.join(" > ");return R(p?`${l}: ${p}`:l)}k={};a.H.push(b);a.I.push(c);for(let [l,p]of Object.entries(b))e=l,h=p,f=e.replace(/\\/g,"\\\\").replace(/\./,"\\."),k[e]=S(a,h,c==null?`${f}`:`${c}.${f}`);return k}catch(l){console.log("Object inspection failed: %o",l)}}try{return R(String(b))}catch(g){console.log("Failed to convert to string: %o",
g);try{return R(String(Object.prototype.toString.call(b)))}catch(l){return`[${d}]`}}};class ja{constructor(){this.cycles={};this.H=[];this.I=[]}};var U=function(a){if(!a.h.__prevent_prod_debug_helper_override){var b=a.h["google.tagmanager.ta.prodqueue"];if(b){T(a,[...b]);var c=b.push;b.push=(...d)=>{T(a,d);return c.apply(b,d)}}else Date.now()-a.T<1E4&&a.h.setTimeout(()=>{U(a)},300)}},T=function(a,b){if(!a.h.__prevent_prod_debug_helper_override)for(let c of b)c.messageType!=="INIT"||a.U.push(c),b=new ja,b={sanitized:S(b,c),cycles:b.cycles},a.j({type:"MEMO",data:{memo:b,sequence:a.M,pageId:a.pageId},uId:""}),a.M++},ka=class{constructor(a,b){this.h=
a;this.j=b;this.T=Date.now();this.M=0;this.U=[];b=new Uint8Array(16);a.crypto.getRandomValues(b);this.pageId=a.btoa(String.fromCharCode(...b)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");U(this)}};function V(a){if(a==null||a.length===0)return!1;a=Number(a);var b=(new Date(Date.now())).getTime();return a<b+3E5&&a>b-9E5};function W(a){return a.replace(/([\?&])gtm_debug=x&/,"$1").replace(/[\?&]gtm_debug=x($|#)/,"$1")};var la=function(a){var b=a.h.document.documentElement.getAttribute("data-tag-assistant-prod-present");if(V(b))a.startProdDebug();else{let c=d=>{d.detail.startProdDebug&&a.startProdDebug();a.h.document.removeEventListener("TADebugSignal",c)};a.h.document.addEventListener("TADebugSignal",c)}},ma=function(a){if(a.h.top===a.h){var b=a.h.document.documentElement.getAttribute("data-tag-assistant-present")||a.h.document.documentElement.getAttribute("data-tag-assistant-prod-present");if(V(b))L(a.B);else{let c=
d=>{d.detail.startDebug&&L(a.B);a.h.document.removeEventListener("TADebugSignal",c)};a.h.document.addEventListener("TADebugSignal",c)}}},na=function(a,b){a.G.push(b);a.O||(a.O=!0,a.h.document.addEventListener("prerenderingchange",()=>{for(let c of a.G)X(a,c);a.G.length=0},{once:!0}))},X=function(a,b){a.h.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:b}))},Y=function(a,b){if(b!=="RESEND_MEMOS"||a.h===a.h.top){b=a.j;var c=Object,d=c.assign,f=a.h,e;var k=W(f.location.href);
var h;if(!(h=f.document.title)&&(h=f.location.href,h!=="/")){try{var g=new URL(h);g.search="";g.hash="";h=g.toString()}catch(l){}g=h.split("/");h=g[g.length-1]||g[g.length-2]}k={href:k,title:h,referrer:W((e=f.document.referrer)!=null?e:""),readyState:f.document.readyState};e=a.h;e=e.google_tag_manager=e.google_tag_manager||{};e=e.debugGroupId||(e.debugGroupId=String(Math.floor(Number.MAX_SAFE_INTEGER*Math.random())));b.call(a,{type:"PAGE_SUMMARY",data:d.call(c,{},k,{groupId:e}),uId:""})}},oa=function(a){a.h===
a.h.top&&(a.D=a.h.setInterval(()=>{a.j({type:"PING",uId:""})},1E3),a.h.document.readyState==="complete"?Y(a):a.h.addEventListener("load",()=>{Y(a)}))},pa=class{constructor(a){this.h=Z;this.S=a;this.G=[];this.O=!1;this.B=new fa(this.h);this.h.document.addEventListener("__TAG_ASSISTANT_API_MESSAGE",b=>{b=b.detail;a:{var c=b==null?void 0:b.type;if(typeof c!=="string")c=!1;else switch(c){case "API_INSTALLED":case "CHECK_DEBUG":case "DISCONNECT":case "PIPE_MESSAGE":case "RECONNECT":case "SIDE_PANEL_ORIGIN":case "WINDOWS_CLOSED":c=
!0;break a;default:c=!1}}if(c)a:if(c=b==null?void 0:b.source,typeof c!=="string")c=!1;else switch(c){case "PAGE":case "EXTENSION":c=!0;break a;default:c=!1}c&&b.type==="PIPE_MESSAGE"&&b.source==="EXTENSION"&&(c=b.data,b=b.origin,c.type!=="SIDE_PANEL"&&(c.type!=="RESEND_MEMOS"||this.receiver||Y(this,"RESEND_MEMOS"),oa(this),this.receiver&&this.receiver(c,b)))});this.h.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:{type:"API_INSTALLED",source:"PAGE"}}));this.h.addEventListener("pagehide",
()=>{this.K!=null&&(this.h.clearInterval(this.K),this.K=void 0)});la(this);ma(this);ea(this.B,b=>{b&&this.j({type:"CONNECTION_ISSUE",data:b,uId:""})})}setReceiver(a){this.receiver=a}sendMessage(a){this.D&&(this.h.clearInterval(this.D),this.D=void 0);this.j(a)}j(a){a={type:"PIPE_MESSAGE",source:"PAGE",data:a,origin:this.h.origin,dId:"",tId:0};this.h.document.prerendering?na(this,a):X(this,a)}disconnect(){this.h.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",{detail:{type:"DISCONNECT",
source:"PAGE"}}));this.S()}startProdDebug(){this.W=this.W||new ka(this.h,a=>{this.j(a)})}};var Z=window;Z.__TAG_ASSISTANT_API||(Z.__TAG_ASSISTANT_API=new pa(()=>{Z.__TAG_ASSISTANT_API=void 0}));}).call(this);
